# 单版本构建工作流 - 用于main分支的快速开发和测试
# 自动构建项目并运行配置的测试，适用于每次推送和提交的拉取请求
# 这有助于捕获仅在特定平台或Java版本上出现的问题，并提供针对错误提交的第一道防线
#
# 注意：此工作流专注于单一版本（当前为Minecraft 1.21.7）的构建
# 如需多版本构建，请使用multi-version-build.yml工作流

name: Single Version Build (Main Branch)
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean
      test_only:
        description: 'Run tests only (skip build)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: setup gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}

      - name: run tests
        run: |
          if [ "${{ inputs.debug_enabled }}" == "true" ]; then
            ./gradlew test --continue --info --stacktrace
          else
            ./gradlew test --continue
          fi

      - name: publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            build/test-results/**/*.xml
          check_name: "Test Results"
          comment_title: "Test Results"
          fail_on: "test failures"

      - name: build project
        if: ${{ inputs.test_only != 'true' }}
        run: |
          if [ "${{ inputs.debug_enabled }}" == "true" ]; then
            ./gradlew build --info --stacktrace
          else
            ./gradlew build
          fi

      - name: upload test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports
          path: |
            build/reports/tests/
            build/test-results/
          retention-days: 30

      - name: upload build artifacts
        uses: actions/upload-artifact@v4
        if: ${{ success() && inputs.test_only != 'true' }}
        with:
          name: mod-jars
          path: |
            build/libs/*.jar
            !build/libs/*-sources.jar
          retention-days: 90

      - name: upload all artifacts (including sources)
        uses: actions/upload-artifact@v4
        if: ${{ success() && inputs.test_only != 'true' }}
        with:
          name: all-artifacts
          path: build/libs/
          retention-days: 30